services:
  wordpress:
    build: .
    volumes:
      - "./wordpress-files:/var/www/html"
    environment:
      - SERVICE_URL_WORDPRESS
      - WORDPRESS_DB_HOST=$SERVICE_DB_HOST_WORDPRESS
      - WORDPRESS_DB_USER=$SERVICE_DB_USER_WORDPRESS
      - WORDPRESS_DB_PASSWORD=$SERVICE_DB_PASSWORD_WORDPRESS
      - WORDPRESS_DB_NAME=$SERVICE_DB_NAME_WORDPRESS
    depends_on:
      - mariadb
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://127.0.0.1"
      interval: 2s
      timeout: 10s
      retries: 10
